// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvCYBx1eY1vGjOAb7lmAKRlDk8PgZAxJc',
    appId: '1:962242235841:web:c33bb0580d4ec8db997340',
    messagingSenderId: '962242235841',
    projectId: 'farmapp-1a612',
    authDomain: 'farmapp-1a612.firebaseapp.com',
    storageBucket: 'farmapp-1a612.firebasestorage.app',
    measurementId: 'G-JPTJTY3W4P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApu24l_vEMFyWhF2jiBRqJo8kG26dJtV4',
    appId: '1:962242235841:android:69c7d251042521ad997340',
    messagingSenderId: '962242235841',
    projectId: 'farmapp-1a612',
    storageBucket: 'farmapp-1a612.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADa_cVsAzuiSXKpKpuOoQrZlvor1c0Hbk',
    appId: '1:962242235841:ios:87069a8e3b8d1894997340',
    messagingSenderId: '962242235841',
    projectId: 'farmapp-1a612',
    storageBucket: 'farmapp-1a612.firebasestorage.app',
    iosBundleId: 'com.example.farmapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADa_cVsAzuiSXKpKpuOoQrZlvor1c0Hbk',
    appId: '1:962242235841:ios:87069a8e3b8d1894997340',
    messagingSenderId: '962242235841',
    projectId: 'farmapp-1a612',
    storageBucket: 'farmapp-1a612.firebasestorage.app',
    iosBundleId: 'com.example.farmapp',
  );
}
